### ISSUE TITLE
Cannot use "make" on MacOS for PhyML

### ISSUE THREAD

**Issue by samandmac** [stephaneguindon/phyml#164]
I've followed the instructions for installation, but when I run `make`, it returns the error:

```
clang: error: the clang compiler does not support '-march=native'

make[2]: *** [main.o] Error 1 

make[1]: *** [all-recursive] Error 1

make: *** [all] Error 2
```

If I use mcpu=apple-a14, it works past that step, but returns multiple errors similar to: 

```
utilities.c:3212:18: error: no member named '_tPij1' in 'struct __ Tree'

boot_tree->_tPij1                                        = tree->_tPij1;

~~~~~~~~~  ^                                          ~~~~  ^
```

Any assistance would be greatly appreciated.
Thank you.

**Comment by stephaneguindon** [comment]
Sorry I missed this one... 
I am not knowledgeable at all on these compilation issues so, unless there's 
someone out there will to help, fixing this will require a bit more time I'm afraid...

**Comment by stephaneguindon** [comment]
I've made some progress on this issue. Would you mind trying the latest commit (b0c75ad93c10e3e3a7c9a956dbca1cb3deb656a9) and let me know if the compilation runs smoothly on you computer?

**Comment by HRG1** [comment]
Thank you, compilation and so far running of phyml and phyml-mpi seem to work fine on macOS 12.4, M1 Max processor.
