### ISSUE TITLE
error: too many arguments to function ‘Write_Tree’

### ISSUE THREAD

**Issue by abrozzi** [stephaneguindon/phyml#115]
Dear Stephane,
thank you first fo all for releasing and maintaining phyml!

I work on a Ubuntu 14.04 LTS machine and following your tutorial I am trying to install phyml-mpi:

``
./configure --enable-mpi; make clean; make;
``

but I get this error:

```
mpi_boot.c:292:11: error: too many arguments to function ‘Write_Tree’
           s = Write_Tree(boot_tree,NO);
           ^
In file included from tiporder.h:35:0,
                 from optimiz.h:23,
                 from lk.h:19,
                 from utilities.h:2354,
                 from mpi_boot.h:19,
                 from mpi_boot.c:13:
io.h:30:7: note: declared here
 char *Write_Tree(t_tree *tree);
       ^
make[2]: *** [mpi_boot.o] Error 1
make[2]: Leaving directory `/home/ab/phyml/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ab/phyml'
make: *** [all] Error 2
```

Where I am wrong?

Bests,
-A

**Comment by stephaneguindon** [comment]
My bad, sorry. I cleaned up a bit the code recently and didn't look carefully enough at the MPI part. It's fixed now. Please pull and compile again. Regards. -Stephane-

**Comment by abrozzi** [comment]
Great! It works now.

Thank you again Stephane,
-A
